version: '3.8'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    environment:
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - "ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}"
      - "ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}"
      - "ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}"
    ports:
      - 5000:5000
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/data:/usr/share/logstash/data
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/logs:/usr/share/logstash/logs
    networks:
      - elastic

volumes:
  elasticsearch_data:

networks:
  elastic: